.PHONY:all
all:Day2 MaxGcd GetDate JudgeLeapYear

Day2:Day2.c
	gcc $^ -o $@
MaxGcd:MaxGcd.c
	gcc $^ -o $@
GetDate:GetDate.c
	gcc $^ -o $@
JudgeLeapYear:JudgeLeapYear.c
	gcc $^ -o $@


.PHONY:clean
clean:
	rm -rf Day2 MaxGcd GetDate JudgeLeapYear
